- .circleci/config.yml
- .gitignore
- binding.gyp
- package-lock.json
- package.json
- scripts/prebuild.js
- scripts/prebuilds.js
- scripts/preinstall.js
- scripts/prepublish.js
- scripts/require-package-json.js
- scripts/should_rebuild.js
- ts/src/heap-profiler-bindings.ts
- ts/src/time-profiler-bindings.ts
I've added our Circle CI prebuild infrastructure. This should mirror the existing prebuild behaviour of dd-trace-js.
cc @rochdev
> build: prebuild with circle ci

- package-lock.json
- package.json
This should fix issues with the prebuild setup.
> build: make sure prebuilds are included and load properly

- .circleci/config.yml
- .github/workflows/ci.yaml
- binding.gyp
- ts/src/sourcemapper/sourcemapper.ts
- ts/test/profiles-for-tests.ts
Added Node.js v18 to the support range. Also simplified the Actions config slightly for now, though that will get redone soon. (Hopefully)
> Add Node.js 18 to CI

- scripts/.eslintrc.json
- scripts/cctest.js
- scripts/prebuild.js
- scripts/prebuilds.js
- scripts/prepublish.js
- scripts/require-package-json.js
- scripts/should_rebuild.js
Just making the scripts follow the same code style as the scripts from the other repos. Makes it easier to keep changes in-sync.
> Make scripts lint style consistent with other repos

- package-lock.json
- package.json
- proto/README.md
- proto/profile.d.ts
- proto/profile.js
- third_party/proto/LICENSE
- third_party/proto/README.google
- third_party/proto/profile.proto
- ts/src/heap-profiler.ts
- ts/src/profile-encoder.ts
- ts/src/profile-serializer.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-cpu-profiler.ts
- ts/test/test-profile-encoder.ts
- ts/test/worker.ts
The output of `pprof-format` is invalid and cannot be decoded by other implementations.
> Revert "Custom pprof encoder"

- ts/src/profile-serializer.ts
For short durations, recomputing the interval is meaningless, therefore bound the interval by intervalMicros and 2 * intervalMicros to ensure that the interval keeps meaningfull values.
> Bound recomputed interval

- package.json
This PR adds support for Node 20 through action-prebuildify that now automatically builds for that version.
> v2.2.0 proposal

- bindings/profilers/heap.cc
When max heap extension count is reached, remove NearHeapLimit callback  until next call to getAllocationProfile.
This is to solve some issues with Node 14, where process would not abort even when return value from callback does not increase the limit and  would result in callback being called multiple times, sometimes even in what appears to be an infinite loop.
> Remove NearHeapLimit callback

- benchmark/sirun/runall.sh
Needed for migration to benchmarking platorm
> Add runall.sh for benchmarks

- ts/src/sourcemapper/sourcemapper.ts
If `DD_PROFILING_DEBUG_SOURCE_MAPS` is set, detailed source map diagnostics are printed with `console.log`
> Allow source map debugging through env variable

- ts/src/sourcemapper/sourcemapper.ts
- ts/test/profiles-for-tests.ts
SourceMapComsumer expects 0-based column numbers
> Fix column number

- package.json
Reverts DataDog/pprof-nodejs#115
> Revert "v3.0.0 proposal"

- bindings/profilers/heap.cc
If reentrancy is detected inside NearHeaplimitCallback (might append when a GC is triggered by profile translation), try to increase heap limit to allow previous callback to succeed.
> Handle reentrancy in NearHeapLimit callback

- package.json
Updates the nan dependency for Node 21
> Upgrade nan for Node 21

- package.json
Increments version on main to `5.0.0-pre`
We need to do it after we released `4.0.0`
> Increment next major on main to 5.0.0-pre

- package-lock.json
- package.json
Bump package version on to 6.0.0-pre
> Bump package version on to 6.0.0-pre

- ts/src/heap-profiler.ts
- ts/src/time-profiler.ts
Fix compatibility with node < 14.18
> Fix compatibility with node < 14.18

- package-lock.json
- package.json
Bumps the nan dep patchlevel
https://github.com/nodejs/nan/pull/989
Fixed a build issue I encountered.
> Bump nan dependency to improve node/v8/electron compat

- .github/workflows/build.yml
- .gitlab/benchmarks.yml
- bindings/profilers/wall.cc
- package.json
> Node 24 support

- .gitlab/benchmarks.yml
Re-enables benchmarks on Node 24
> Enable benchmarks on Node 24

- ts/src/index.ts
Missed adding getMetrics in one spot
> Missed adding getMetrics in one spot
