- bindings/profiler.cc
- ts/src/time-profiler.ts
- ts/test/test-time-profiler.ts
- ts/test/test-worker-threads.ts
This introduces an argument to the stop function to tell it to start a new profile, by calling the stop function repeatedly you can keep getting more profiles. By making this an argument it allows for the ordering of start and stop to be rearranged depending on the Node.js version. This is important as pre-16 needs to dispose the profiler between profiles to avoid a memory leak, while 16+ needs to start the next profile before stopping the previous to prevent a latency spike due to tearing down and starting up the symbolizer thread on each stop and start.
> Fix CPU profiler latency

- .circleci/config.yml
- package.json
- scripts/prebuild.js
This adds Apple Silicon support and runs tests across more version and OS combos. I've also taken the check task out of `posttest` as the `gts` module is currently broken by `prettier` making breaking changes in a minor.
> Update CircleCI config

- package-lock.json
- package.json
The PR is essentially to bump [protobufjs](https://github.com/protobufjs/protobuf.js) to version [6.11.3](https://github.com/caolan/async/blob/master/CHANGELOG.md#v322) to fix a [prototype pollution exploit](https://security.snyk.io/vuln/SNYK-JS-PROTOBUFJS-2441248) found in versions < 6.11.3 . 
The vulnerability is labelled as `High Severity`.
> [security] Bump protobufjs to version 6.11.3

- .circleci/config.yml
- package-lock.json
- package.json
- scripts/should_rebuild.js
Because there are prebuilds for all supported platforms, we can exclude the binding.gyp from the package and remove the install script from package.json
> Eliminate install script

- .github/workflows/release.yml
action-prebuildify has its own concurrency control which makes the one here cancel it out. Since publish depends on the build workflow anyway, it's best to just remove it altogether.
> Remove concurrency cancel from release job

- package.json
These dependencies are only used in dev and were already present in `devDependencies`.
> remove rimraf and semver from dependencies

- ts/src/cpu-profiler.ts
- ts/src/profile-serializer.ts
- ts/src/v8-types.ts
This change fixes several issues:
* Measured cpu time is not used for samples with labels when converted to CpuProfile: samples with labels are assigned the sampling period, which is incorrect since based on wall clock
* During conversion to CpuProfile, all samples are treaded as having labels (and thus are impacted by the previous issue). This is because when no labels are set, the empty object `{}` is stored in CpuProfiler.labels (by NativeCpuProfiler._exit in cpu.js), and this empty object is added to CpuProfileNode.labelSets.
* CPU time of samples without labels is incorrectly reported since all cpu time measured for a CpuProfileNode (with or without labels) is assigned to the samples without labels
To fix theses issues, following changes are made during conversion to CpuProfile:
* …
> Store cpu time per LabelSet in CpuProfile

- bindings/profilers/cpu.cc
- bindings/profilers/cpu.hh
- bindings/test/profilers/cpu.test.cc
If several samples are captured before symbolizer has a chance top run, then only the last one will be accounted for.
This change introduces a ring buffer (whose size is arbitrarily set to 100), that stores captured samples.
Symbolizer processes all samples present in the ring buffer instead of a single one.
> Add a ring buffer to store samples between capture and symbolization

- bindings/sample.cc
`push_back` is replaced by direct indexing since `std::vector<uintptr_t> output(n);` already creates a a vector with n elements (set to 0).
> Fix frame vector size

- bindings/profilers/cpu.cc
- bindings/profilers/cpu.hh
SetLabels / CaptureSample / ProcessSamples are all executed by the javascript thread, and therefore no synchronization is needed.
> Remove mutex from cpu profiler

- bindings/profilers/cpu.cc
- bindings/profilers/cpu.hh
Crashes were caused by SamplerThread calling `Isolate::RequestInterrupt` during Node shutdown.
Fix this by adding a cleanup hook with `node::AddEnvironmentCleanupHook` that stops the profiler upon node exit.
> Fix random CPU profiler crash during node shutdown

- ts/src/profile-serializer.ts
- ts/src/time-profiler.ts
- ts/test/profiles-for-tests.ts
- ts/test/worker.ts
The effective sampling interval of wall profiler is larger than the requested one. Eg. when requesting a 99Hz sampling rate (~10.1ms sampling interval), we observe an average sampling interval of ~12.5ms. This discrepancy leads to an underestimation of CPU consumption since samplesare weighted by the samping interval. To fix this discrepancy we recompute the average samping interval from profile duration and total number of hits, since profile duration should be #hits x mean interval.
> Recompute wall profiler sampling interval

- ts/test/test-cpu-profiler.ts
* Remove stubs since they were not used, and ensuring that they are used would probably make the test fail
* Set labels before starting the profiler since the profiler will request an interrupt as soon as the sampling thread is started and this leads to a race condition on labels.
> Fix flaky unit test

- ts/src/sourcemapper/sourcemapper.ts
When calling sites line numbers are reported (StartProfiling called with CpuProfilingMode::kCallerLineNumbers), sometimes locations point to the part of a code line before the first word. In that case, SourceMapConsumer.originalPositionFor will locate with a binary search the first generated position less or equal to the input. Since the input location does not point to a generated location and is at the start of a line, the binary search will return the last generated location from the previous line. But since the found location is on a different line from the input location, originalPositionFor will return null.
Changes done to fix this:
* do a first search with LEAST_UPPER_BOUND instead of GREATEST_LOWER_BOUND: binary search will search for the first element greater or equal to the …
> Fix sourcemap lookup when line numbers are enabled

- bindings/profilers/cpu.hh
Currently latest sample is dropped when buffer is full, therefore this bug does not occur.
> Fix push when sample buffer is full

- .circleci/config.yml
node:12 image is based on debian stretch distribution which has reached EOL. Deb repositories in this image are incorrect because they have been moved to archide.debian.org:
* deb.debian.org -> archive.debian.org
* security.debian.org -> archive.debian.org/debian-security/ 
The easy fix is to use node:12-buster instead.
> Fix circle CI for node 12

- bindings/location.cc
- bindings/location.hh
- bindings/per-isolate-data.cc
- bindings/per-isolate-data.hh
- bindings/profilers/wall.cc
- bindings/sample.cc
- bindings/test/location.test.cc
- ts/test/test-worker-threads.ts
- ts/test/worker.ts
Wall profiler's JS class' constructor was not maintained per-isolate but instead in a static. This caused a segfault in a node process using Worker API because every worker has its own isolate. If a new worker started up after the worker (and isolate) to which the current value of the constructor handle belonged, the handle would attempt to release its old value, which at that time is a dangling pointer, causing a segfault.
* I modified the `worker.ts` test to run two workers one after the other, the second launching after the first one was destroyed. This caused a segfault in 100% of the attempted (many) runs. 
* After confirming that we have a reproducer in the test, a fix was devised to use the existing `PerIsolateData` data structure and have it also manage this class' constructor. …
> Wall profiler constructor not maintained per-isolate

- .github/workflows/build.yml
The end goal is to disallow merging pull requests that have a failed check. Trouble is that you need to specify manually each check that is required for merging in github UI and in the case of a matrix job such as build, this represents around 20 different checks. The solution is to create a new job that depends on the other jobs and check the status of this job (but there are some [additional](https://github.com/orgs/community/discussions/26733) [caveats](https://github.com/orgs/community/discussions/26822)).
> Add a gatekeeper job to easily make PRs fail

- .circleci/config.yml
- package.json
This makes pprof-nodejs installable from a git branch: npm install DataDog/pprof-nodejs#some_branch
This works because npm invokes prepare script when fetching git dependencies and in that case also install package dev dependencies. This does not work with yarn though...
> Make package installable from git branch

- ts/src/sourcemapper/sourcemapper.ts
This reverts commit cfebbb3c94fb700e286f919ead74dd0bab0dff81.
This commit resulted in failure to get original function name back for source maps generated by webpack.
> Revert "Fix sourcemap lookup when line numbers are enabled (#81)"

- ts/src/index.ts
- ts/src/logger.ts
- ts/src/sourcemapper/sourcemapper.ts
- ts/test/profiles-for-tests.ts
* Allow to inject logger in profiler
* Use logger to debug source maps
* Work around faulty file path in webpack sourcemaps:
With nextjs/webpack, when there are subdirectories in `pages` directory, the generated source maps do not reference correctly the generated files in their `file` property.
For example if the generated file / source maps have paths:
<root>/pages/sub/foo.js(.map)
foo.js.map will have ../pages/sub/foo.js as `file` property instead of ../../pages/sub/foo.js
To workaround this, check first if file referenced in `file` property exists and if it does not, check if generated file exists alongside the source map file.
> Improve source maps

- bindings/profilers/wall.cc
- ts/src/profile-serializer.ts
- ts/test/test-worker-threads.ts
- ts/test/worker.ts
`init_` was never set to true leading to reinitialization of the whole map each time a profiler was added/removed.
> Fix bug in profiler map

- bindings/profilers/wall.cc
- bindings/profilers/wall.hh
- package-lock.json
- ts/src/index.ts
- ts/src/time-profiler.ts
- ts/test/test-time-profiler.ts
v8 profiler event processor thread sometimes get stuck in a loop eating 100% CPU, leading to empty profiles.
This pull-request tries to accomplish goals:
* Make the bug less likely to happen by waiting for profiler signal before and after starting a new profile
* Detect if the bug has occurred (by checking for profiles with no hits or no non-ticks samples), and in that case fully stop and restart the profiler to reset the profile to a valid state.
> Workaround v8 bug

- tsconfig.json
Upgrades TypeScript compiler settings to target ES2020. We already used ES2020 as the `lib` but were stuck on ES2019 as the `target`.
I'd like to use a bigint literal in a test soon. [dd-trace-js](https://github.com/DataDog/dd-trace-js/blob/master/.eslintrc.json#L3) also uses ES2020. It's a good choice for Node 14 and above.
> Target ES2020 language

- binding.gyp
- bindings/profilers/wall.cc
- ts/src/profile-serializer.ts
- ts/src/time-profiler.ts
- ts/src/v8-types.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-time-profiler.ts
Adds a timestamp to the sample context objects exposed to JS. Previously, whatever was set with `context` setter on the profiler would be returned as the context object to `generateLabels` in the serializer. This is now changed, and instead an object is returned with structure `{ context: theContextObject, timestamp: epochTsMicros }` where `theContextObject` is the object set as the label context, and `epochTsMicros` is a bigint value, a number of microseconds since UNIX epoch marking the end timestamp of capturing the sample.
This will allow us to emit `end_timestamp_ns` label from the wall profiler in dd-trace, making it possible to visualize the time of sampling on timelines.
This PR is currently based on #132 not out of …
> Emit sample timestamps

- bindings/profilers/heap.cc
- ts/src/heap-profiler-bindings.ts
- ts/src/heap-profiler.ts
In a worker thread, OOM is not fatal to the whole process and will only This is done by a callback registered by node, that's why we remove our callback and then call `LowMemoryNotification()` to trigger another garbage collection, which will eventually call the callback registered by node.
> Avoid OOM abort in worker thread

- ts/src/heap-profiler.ts
- ts/src/profile-serializer.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-heap-profiler.ts
`HeapProfiler.profile()` takes a new argument: a function that takes an`AllocationProfileNode` and returns a `LabelSet`.
Allow adding labels to heap profiles.
> Add labels to heap profiler

- ts/src/profile-serializer.ts
- ts/src/time-profiler.ts
- ts/test/test-time-profiler.ts
* Make context argument to `generateLabels` optional
* Call `generateLabels` for unlabelled hits without arguments
Allow adding labels to samples without contexts.
> [PROF-8802] Allow adding labels to wall profile even when contexts are not enabled

- package-lock.json
Bump major version in package-lock.json
> Bump major version in package-lock.json

- .github/workflows/build.yml
- binding.gyp
- bindings/binding.cc
- bindings/defer.hh
- bindings/profilers/wall.cc
- bindings/profilers/wall.hh
- bindings/test/binding.cc
- package.json
- scripts/cctest.js
- suppressions/lsan_suppr.txt
- ts/src/time-profiler.ts
- ts/test/test-time-profiler.ts
* Compile and run tests with address sanitizer in CI
* Add target to compile and run tests with thread sanitizer (not run in CI because of errors)
* Run tests with valgrind in CI
* Fix warnings and turn warnings into errors on Linux and MacOS
* Manually destroy native WallProfiler object upon stop:
GC is not guaranteed to run and native object might not be destroyed and worker threads in particular could leak memory.
* Enable c++17 for all platforms
* Disable build on armv7
> [PROF-8678] Run tests with address sanitizer

- bindings/profilers/heap.cc
- ts/test/test-heap-profiler.ts
uv_fs_mkstemp() is not used because it fails unexpectedly on Windows (fail fast exception is raised when trying to write to the returned file descriptor.
> Make OOM test work on Windows

- bindings/profilers/wall.cc
- ts/src/profile-serializer.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-profile-serializer.ts
- ts/test/worker.ts
This fix two bugs related to non-JS threads CPU time reporting:
* Avoid computing/reporting non-JS threads CPU time when CPU profiler is not enabled
* Report zero wall time in non-JS threads CPU time sample: all contexts with labels for a given profile node were counted as one wall time sample 
> Make sure to not report wall time as part of non-JS threads

- ts/src/profile-serializer.ts
- ts/src/sourcemapper/sourcemapper.ts
Add support for mjs/cjs source maps:
* Look for `.js.map` / `.mjs.map` / `.cjs.map`
* Remove `file://` prefix present in locations from `.mjs` files
Support bundles generated with esbuild with `--format=esm`.
> [PROF-9213] Add support for mjs/cjs source maps

- .github/workflows/release.yml
Skip build on arm and linux-32 on release branches (similarly to what is done on main branch).
> Fix build on release branches

- package-lock.json
- package.json
- ts/src/profile-encoder.ts
Uses `Profile.encodeAsync()` from pprof-format 2.1.0 in the profile encoding method.
Lowering the latency spikes caused by profile encoding.
Existing `profile-encoded/encode` test fails when this is broken.
> PROF-9395: Use `Profile.encodeAsync()`

- package-lock.json
- package.json
- ts/src/profile-encoder.ts
**Release v5.2.0**:
Improvement: Profile encoding uses more asynchronous stages, making 
> V5.2.0 proposal

- .github/workflows/build.yml
- .github/workflows/release.yml
Update `actions/download-artifacts` to v4.
This is required following the update of `actions/upload-artifacts` to v4 in prebuildify.
> Update actions/download-artifacts to v4

- .github/workflows/build.yml
- .github/workflows/release.yml
Only retrieve `prebuilds` artifact.
No need to retrieve all artifacts and merge them.
> Download artifact from prebuilds job

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
- bindings/profilers/wall.cc
- bindings/profilers/wall.hh
- package-lock.json
- package.json
> Remove support for node 14

- .github/workflows/build.yml
- .github/workflows/release.yml
* Fixes release artifact download to conform to https://github.com/DataDog/action-prebuildify/pull/43
* Tries to fix permissions for tagging the repo on release.
Jira: [PROF-10740] (still trying to do a release for Node 23)
[PROF-10740]: https://datadoghq.atlassian.net/browse/PROF-10740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix artifact download

- .github/workflows/release.yml
* Undoes the bad fix for permissions for tagging the repo on release.
Jira: [PROF-10740] (still trying to do a release for Node 23)
[PROF-10740]: https://datadoghq.atlassian.net/browse/PROF-10740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert the incorrect fix for tagging permissions

- .gitlab/benchmarks.yml
Disable benchmark run on tags.
Baseline commit determination in benchmarks fails when gitlab pipeline is triggered by a tag.
> Disable benchmark run on tags

- bindings/profilers/wall.cc
- bindings/profilers/wall.hh
- ts/src/profile-serializer.ts
- ts/src/v8-types.ts
- ts/test/test-time-profiler.ts
Captures `node::AsyncHooksGetExecutionAsyncId` with wall/CPU samples and exposes it as `TimeProfileNodeContext.asyncId` to downstream users – this can typically be leveraged from `generateLabels` implementations.
By correlating timestamped samples with Node async IDs we can detect longer executions within the same async context, indicating a blocked event loop. We already do this but rely on tracing span IDs; this solution makes this profiler capability independent of tracing.
The `AsyncHooksGetExecutionAsyncId` API returns `-1` when it can't find the `node::Environment` in the current `v8::Context`. There are some operations that V8 turboshaft compiler intrinsifies – e.g. `Date.now()` and some string operations – and those …
> Capture Node execution async ID with samples

- bindings/profilers/wall.cc
Retrieves the `Isolate` and its current `Context` once and uses it for all operations in `WallProfiler::GetContextsByNode`
> Don't use `Nan` in `WallProfiler::GetContextsByNode`

- bindings/profilers/wall.cc
Removes a conditional for `V8_MAJOR_VERSION` < 8
Even Node 16.0.0, the oldest we support defines `V8_MAJOR_VERSION` as 9.
> Remove conditionals for V8_MAJOR_VERSION < 8

- bindings/translate-heap-profile.cc
- bindings/translate-time-profile.cc
- bindings/translate-time-profile.hh
See #193 – it tries to whack few more FP register use moles.
JIRA: [PROF-11193]
[PROF-11193]: https://datadoghq.atlassian.net/browse/PROF-11193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> More prohibition of fp register use

- bindings/profilers/wall.cc
Disables async ID capture in the signal handler.
Customer crashes. We need to disable it quickly as it is not being actively used yet, and figure out a longer term solution later.
> Don't capture async IDs for the time being

- bindings/profilers/wall.cc
- ts/src/profile-serializer.ts
- ts/src/v8-types.ts
- ts/test/test-time-profiler.ts
Changes previous behavior where Node.js profiler dropped idle samples from its final pprof file output. It now keeps them and no longer rolls up their CPU time to the next non-idle sample. It also set their wall time to zero.
Keeping idle samples this way has several benefits:
* It gives us evidence that sampling happened.
* We can use them to break event loop blocking strides that would falsely look continuous if we discarded such samples.
* We can detect reductions in sampling rate and thus deterioration of profiling quality. It’s currently unclear how would we communicate this to the user.
* It gives us a more realistic view of CPU times. Even a 0,5% of CPU usage while idle will add up to 50% CPU usage over 100 samples (normally, 1s), and …
> Preserve idle samples with zero wall time and no CPU time rollup

- bindings/profilers/wall.cc
- bindings/profilers/wall.hh
- ts/src/time-profiler.ts
- ts/test/test-time-profiler.ts
Reenables async ID collection with guards. Prevents collecting async ID when either GC is ongoing (captures the ID at the GC prologue) or when the isolate has no current context.
We want to safely collect async ID.
Jira: [PROF-11265]
[PROF-11265]: https://datadoghq.atlassian.net/browse/PROF-11265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Only collect async ID when it's safe to do so

- binding.gyp
xcode 16.3 ships with clang17 as default compiler. This version of clang warns about casts between incompatible function types, and nan does some of them:
```
include/node/v8-persistent-handle.h:512:26: error: cast from 'typename WeakCallbackInfo<ObjectWrap>::Callback' (aka 'void (*)(const WeakCallbackInfo<ObjectWrap> &)') to 'Callback' (aka 'void (*)(const WeakCallbackInfo<void> &)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch]
```
This commit adds a -Wno-cast-function-type-mismatch flag to the compiler flags to suppress these warnings (that would otherwise cause errors because of the -Werror flag).
> Fix compilation with xcode 16.3

- bindings/profilers/heap.cc
v8 destroys the heap profiler after the heap spaces which can cause crashes: https://github.com/nodejs/node/blob/v24.0.1/deps/v8/src/heap/heap.cc#L6227-L6246
This workaround stops the heap profiler before the heap spaces are destroyed.
> Workaround for v8 crash

- bindings/profilers/wall.cc
Uses `node::AsyncHooksGetExecutionAsyncId(Local<Context>)` API on Node 24 with context obtained through `v8::Isolate::GetEnteredOrMicrotaskContext()`. This API works in GC and also shouldn't cause sporadic crashes on worker threads.
Jira: [PROF-11628]
[PROF-11628]: https://datadoghq.atlassian.net/browse/PROF-11628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use AsyncHooksGetExecutionAsyncId(Context) API on Node 24

- .github/workflows/release.yml
Updates min-node-version in release.yml to 18
Can't ship a release without fixing this as #215 uses V8 API present in 18+.
JIRA: [SCP-759]
[SCP-759]: https://datadoghq.atlassian.net/browse/SCP-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update min-node-version in release.yml to 18

- README.md
Apparently the badges still pointed to the original Google version. 😅
> Fixed package badge

- package-lock.json
- package.json
- ts/test/profiles-for-tests.ts
Bumps TypeScript version
Otherwise we get failures such as https://github.com/DataDog/pprof-nodejs/actions/runs/17212572964/job/48827916928?pr=229
> Bump TypeScript as otherwise CI can no longer compile

- package-lock.json
- package.json
- ts/src/profile-serializer.ts
- ts/src/time-profiler.ts
- ts/test/test-time-profiler.ts
Optimization: allows declaring some label names as low-cardinality for the time profile serialization. The `Label` objects will be deduplicated for these labels.
dd-trace-js emits 3 fixed labels for every sample (thread name, thread ID, thread OS ID.) Because of timeline sample disaggregation, this means roughly 20k label objects are created in memory just for them. With deduplication, we'll only create 3 label objects instead.
For this to have effect, we need to also land https://github.com/DataDog/pprof-format/pull/26 and release a new `pprof-format` version.
> Optimization: allows declaring some labels as low-cardinality

- bindings/profilers/wall.cc
- ts/test/test-time-profiler.ts
- ts/test/worker.ts
- ts/test/worker2.ts
Enables async ID collection and CPED storage of sample contexts in more tests.
We want the features to run as widely as possible in tests. We enable them in worker tests (although we don't check the results – we mostly want to make sure there are no crashes) and also in the larger label testing in `test-time-profiler.ts`
It's all tests. 
**Additional information**:
The tests uncovered the issue with requesting async ID when there are no free handles for Locals and it needs one Local slot. We added safeguards to bail out of requesting async ID if we know it would trigger allocation of a new array for locals.
> Test new features in more places
